include:
  - ros-goat-controller/docker-compose.yml

services:  
  nginx:
    image: docker.io/library/nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/bags:/bags
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/foxglove/default-layout.json
    ports:
      - 8080:8080
    restart: always

  ros-foxglove-bridge:
    image: ghcr.io/rosblox/ros-foxglove-bridge:humble
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment="ROS_DOMAIN_ID" /run.sh

  ros-joy-linux:
    image: ghcr.io/rosblox/ros-joy-linux:humble
    restart: always
    network_mode: "host"
    volumes:
      - /dev/input:/dev/input
    privileged: true
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment="ROS_DOMAIN_ID" /run.sh


  rtklib:
    image: ghcr.io/rosblox/rtklib:latest
    restart: always
    command: str2str -in ntrip://$NTRIP_USER:$NTRIP_PASSWORD@www.swipos.ch:2101/MSM_GISGEO_LV95LHN95 -b 1 -out tcpcli://192.168.60.1:6666

  ros-septentrio-gnss-driver:
    image: ghcr.io/rosblox/ros-septentrio-gnss-driver:humble
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: su - ros --whitelist-environment="ROS_DOMAIN_ID" /run.sh

  ros-bag-recorder:
    image: ghcr.io/rosblox/ros-bag-recorder:humble
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    working_dir: /bags    
    volumes:
      - ~/bags:/bags
      - ./ros-bag-recorder/qos_override.yaml:/qos_override.yaml
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID  -c 'source /opt/ros/humble/setup.bash; cd /bags; ros2 bag record --max-cache-size 1000000000 -s mcap  --qos-profile-overrides-path /qos_override.yaml  --max-bag-size 200000000 /commanded_velocity /measured_velocity /current_consumption'
